name: "Update Solana"
description: "Updates workspace dependencies to the latest stable release version of Solana"
branding:
  icon: box
  color: yellow
runs:
  using: "composite"
  steps:
    - name: Set env variables
      run: echo "SOLANA_VERSION=$(curl -sL https://api.github.com/repos/solana-labs/solana/releases | jq -r 'map(select(.name | startswith("Mainnet"))) | first | .tag_name' | cut -d'v' -f 2)" >> $GITHUB_ENV
      shell: bash
    - name: Bump dependency versions
      run: | 
        tomls=$(find "." -name Cargo.toml)
        for toml in "${tomls[@]}" 
        do 
          sed -i -e "s#\(solana-[a-zA-Z-]* = \"\)[^\"]*\(\"\)#\1$SOLANA_VERSION\2#g" $toml
        done
      shell: bash
